## Numpy array and basic


In [1]:
import numpy as np

## creating array from list

In [3]:
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)
arr_2d = np.array([[10, 20, 30, 40, 50],[60, 70, 80, 90, 100]])
print("2D Array:", arr_2d)

1D Array: [10 20 30 40 50]
2D Array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


## Difference between list and numpy

In [8]:
py_list = [10, 20, 30, 40, 50]
print("Pyhton list: ", py_list*2)

np_array = np.array([10, 20, 30, 40, 50]) #element wise multiplication
print("Numpy array: ", np_array*2)


import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print(" \n Python list time: ", time.time() - start)

start = time.time()
np_array = np.arange(100000)
print("\n Numpy array time: ", time.time() - start)

Pyhton list:  [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
Numpy array:  [ 20  40  60  80 100]
 
 Python list time:  0.024636507034301758

 Numpy array time:  0.0


## creating array from scratch

In [18]:
zeros = np.zeros((3,4))
print("zeros array: \n" , zeros)

ones = np.ones((2,4))
print("zeros array: \n" , ones)

full = np.full((2,5), 8)
print("full array: \n" , full)

random = np.random.rand(3,3)
print("random array: \n" ,(random))

sequences = np.arange(0,10,2)
print("sequences array: \n" , sequences)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[8 8 8 8 8]
 [8 8 8 8 8]]
random array: 
 [[0.6853633  0.71594759 0.04460836]
 [0.46654039 0.64097764 0.68946582]
 [0.44108236 0.81834372 0.06654461]]
sequences array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [ ]:
import numpy as np
vector = np.array([1,2,3])
print("Vector :", vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix :\n", matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor :\n", tensor) #Tensor matlb multiple dimensional array

Vector : [1 2 3]
Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
