## Numpy Array operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7] )
print("Slicing with step", arr[1:8:2] )
print("Negative Indexing", arr[-5] )

Basic Slicing [3 4 5 6 7]
Slicing with step [2 4 6 8]
Negative Indexing 6


In [8]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Specific Element :", arr_2d[1,3])  #Element at 2nd row and 4th column
print("Entire row:", arr_2d[0, :])   #Entire first row
print("Entire column:", arr_2d[:, 2])  #Entire third column

Specific Element : 9
Entire row: [1 2 3 4 5]
Entire column: [ 3  8 13]


## Sorting

In [ ]:
unsorted_arr = np.array([5,2,9,1,5,6])
sorted_arr = np.sort(unsorted_arr)
print("Unsorted Array:", unsorted_arr)
print("Sorted Array:", sorted_arr)

#other way
add_2d_unsorted = np.array([[3,1,2],[6,4,5]])
add_2d_sorted = np.sort(add_2d_unsorted, axis=1)  #Sort along rows
print("Unsorted 2D Array:\n", add_2d_unsorted)
print("Sorted 2D Array along rows:\n", add_2d_sorted)

Unsorted Array: [5 2 9 1 5 6]
Sorted Array: [1 2 5 5 6 9]
Unsorted 2D Array:
 [[3 1 2]
 [6 4 5]]


## Filter

In [2]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers:", even_number)

Even Numbers: [ 2  4  6  8 10]


## Filter with mask

In [3]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy inddexing vs np.where()

In [6]:
indices = [0, 2, 4, 5]
print(numbers[indices])  #Output: [1 3 5]

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ", numbers[where_result])

[1 3 5 6]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print("Condition Array:", condition_array)

Condition Array: [ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6])
combined = arr1 + arr2
# combined = np.concatenate((arr1, arr2, arr3))
print(combined)



[5 7 9]


## Array Compatibility

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([6, 7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [16]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack([original, new_row])
print(original)
print(with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack([original, new_col])
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [17]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)  #Delete element at index 2
print("Original Array:", arr) 
print("Array after deletion:", deleted)

Original Array: [1 2 3 4 5]
Array after deletion: [1 2 4 5]
